articles/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<article_pk>\d+)/(?P<background_pk>\d+)/$', views.background_detail, name="background"),
    url(r'(?P<pk>\d+)/$', views.article_detail, name="detail"),
    url(r'writer/(?P<pk>\d+)/$', views.writer_detail, name="writer"),
    url(r'^$', views.article_list, name="list"),
]

newspaper/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar

from . import views

urlpatterns = [
    url(r'^articles/', include("articles.urls", namespace="articles")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^$', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    headline = models.CharField(max_length=255)
    publish_date = models.DateTimeField(auto_now_add=True)
    content = models.TextField()

    def __str__(self):
        return self.headline

class Background(models.Model):
    headline = models.CharField(max_length=255)
    content = models.TextField(blank=True, default="")
    order = models.IntegerField(default=0)
    article = models.ForeignKey(Article)

    class Meta:
        ordering = ["order",]

    def __str__(self):
        return self.headline

class Writer(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(default="writer@newspaper.com")
    bio = models.TextField(default="This writer is quite interesting but unspecific.")

articles/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Article, Background, Writer

# Create your views here.
def article_list(request):
    articles = Article.objects.all()
    return render(request, "articles/article_list.html", {"articles" : articles})

def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    return render(request, "articles/article_detail.html", {"article" : article})

def background_detail(request, article_pk, background_pk):
    background = get_object_or_404(Background, article_id=article_pk, pk=background_pk)
    return render(request, "articles/background_detail.html", {"background" : background})

def writer_detail(request, pk):
    writer = Writer.objects.get(pk=pk)
    return render(request, "articles/writer_detail.html", {"writer" : writer})

newspaper/views.py
from django.http import HttpResponse
from django.shortcuts import render

def index(request):
    return render(request, "home.html")

articles/templates/articles/article_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load article_extras %}

{% load static from staticfiles %}

{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'articles/css/style.css' %}" />{% endblock %}

{% block title %}{{ article.headline }}{% endblock %}

{% block content %}
<article>
    <h2>{{ article.headline }}</h2>
    {{ article.content|linebreaks }}

    <section>
        <p><b>Want more background to this article? Take a look at the following {{ article.background_set.all|length }} background article{{ article.background_set.count|pluralize}}: {{ article.background_set.all|join:", " }}</b></p>
        
        {% for background in article.background_set.all %}
            <h3><a href="{% url 'articles:background' article_pk=background.article.pk background_pk=background.pk %}">{{ background.headline }}</a></h3>
            {% with con=background.content %}
                <b> Content: {{ con|wordcount }} words. Estimated time to read: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}</b>
            {% endwith %}
        {% endfor %}
    </section>

</article>
{% endblock %}

articles/templates/articles/article_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'articles/css/style.css' %}" />{% endblock %}
{% block title %}Articles{% endblock %}

{% block content %}

<div class="cards">
    {% for article in articles %}
    <div class="card">
        <header><a href="{% url 'articles:detail' pk=article.pk %}"><h3>{{ article.headline }}</h3></a></header>
        <div class="card-copy">
            {% if article.content|wordcount <= 5 %}
                {{ article.content }}
            {% else %}
                {{ article.content|truncatewords:5 }}
                <a href="{% url 'articles:detail' pk=article.pk %}">Read More</a>
            {% endif %}
            <div>Created on: {{ article.created_at|date:"d/m/y" }}</div>
        </div>
    </div>
    {% endfor %}
    <div>If you have any comments on the articles, please send them to: {{ email|urlize }}</div>
</div>
{% endblock %}

articles/templates/articles/article_nav.html
{% for article in articles %}
    <div><a href="{% url 'articles:detail' pk=article.pk %}">{{ article.headline }}</a></div>
{% endfor %}

articles/templates/articles/background_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}
{% load article_extras %}

{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'articles/css/style.css' %}" />{% endblock %}

{% block title %}{{ background.headline }} - {{ background.article.headline }}{% endblock %}

{% block content %}
<article>
    <h3>{{ background.headline }}</h3>

    {% with con=background.content %}
        {{ con|linebreaks }} <b>Content: {{ con|wordcount }} words. Estimated time to read: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}</b>
    {% endwith %}

</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}
{% load static from staticfiles %}


{% block title %}Turn The Page{% endblock %}
{% block static %}<link rel="stylesheet" type="text/css" href="{% static 'articles/css/style.css' %}" />{% endblock %}

{% block content %}
    <h1>The Daily Reef</h1>
{% endblock %}

templates/layout.html
{% load static from staticfiles%}
{% load article_extras %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta http-equiv="content-type" content="text/html">
        <link href="https://fonts.googleapis.com/css?family=Lobster|Lobster+Two|Poiret+One" rel="stylesheet">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container">
            <div class="article-nav">{% nav_articles_list %}</div>
            <nav>
                <a href="{% url 'index' %}"><h4>Home</h4></a>
                <a href="{% url 'articles:list' %}"><h4>Articles</h4></a>
            </nav>
            </p><b>Don't miss our latest article, {% latest_article %}!</b></p>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>